# Generated by Django 4.2.5 on 2024-02-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobOffer',
            new_name='JobOffers',
        ),
    ]
